#ifndef MONGO_BASE_DEFINES_HPP_INCLUDED
#define MONGO_BASE_DEFINES_HPP_INCLUDED



// boost filesystem defines
#define BOOST_FILESYSTEM_VERSION 3
#define BOOST_FILESYSTEM_NO_DEPRECATED


#endif // MONGO_BASE_DEFINES_HPP_INCLUDED
